services:
  # Backend API Service
  - type: web
    name: qzonme-api
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_aowkVxcMf1y7@ep-dry-wave-a68wrryp-pooler.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: TOGETHER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: GOOGLE_VISION_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /health
    
  # Static Site for Frontend
  - type: static
    name: qzonme-frontend
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build:client
    staticPublishPath: ./client/dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
